version: 2.1

#  aws-s3: circleci/aws-s3@3.0

orbs:
  browser-tools: circleci/browser-tools@1.2.3

#      - aws-s3/sync:
#          from: /tmp/html/
#          to: s3://readthedocs-static-dev/qa/theme/${CIRCLE_BRANCH}/

commands:
  build_html:
    description: 'Build HTML'
    steps:
      - run: make install
      - run: make build
  run_happo:
    description: 'Run Happo'
    steps:
      - run: make diff

jobs:
  build:
    description: 'Build'
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - checkout
      - build_html
      - persist_to_workspace:
          root: /tmp/html
          paths: '*'
  happo:
    docker:
      - image: 'cimg/node:lts-browsers'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/html
      - browser-tools/install-browser-tools
      - run_happo

workflows:
  version: 2
  tests:
    jobs:
      - build
      - happo:
          requires:
            - build
