version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3
  cypress: cypress-io/cypress@1.27.0

commands:
  build_html:
    description: 'Build HTML'
    steps:
      - run: make install
      - run: make build

jobs:
  build:
    description: 'Build'
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - checkout
      - build_html
      - persist_to_workspace:
          root: /home/circleci/project/docs/_build/
          paths: '*'
  happo:
    docker:
      - image: 'cimg/node:14.18-browsers'
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci/projects/docs/_build/
      - browser-tools/install-browser-tools
      - cypress/run:
        name: Run Cypress with Happo
        command-prefix: 'npx happo-cypress -- npx'

workflows:
  version: 2
  tests:
    jobs:
      - build
      - happo:
          requires:
            - build
