version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3
  cypress: cypress-io/cypress@1.27.0

commands:
  build_html:
    description: 'Build HTML'
    steps:
      - run: make install
      - run: make build

jobs:
  build:
    description: 'Build'
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - attach_workspace:
          at: ~/
      - build_html
      - persist_to_workspace:
          root: ~/
          paths:
            - project

workflows:
  test:
    jobs:
      - cypress/install
      - build:
          requires: cypress/install
      - cypress/run:
          name: Run Cypress with Happo
          command-prefix: 'npx happo-cypress -- npx'
          attach-workspace: true
          requires:
            - build
