version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0

commands:
  build_html:
    description: "Build HTML"
    steps:
      - run: pip install --user -r requirements.txt
      - run: sphinx-build -t html docs/ /tmp/html
      - run: find /tmp/html
      - aws-s3/sync:
          from: /tmp/html/
          to: s3://readthedocs-static-dev/qa/theme/${CIRCLE_BRANCH}/
  run_happo:
    description: "Run Happo"
    steps:
      - run: npm ci
      - run: npm run happo-ci-circleci

jobs:
  build:
    description: "Build"
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - checkout
      - build_html
  happo:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - run_happo

workflows:
  version: 2
  tests:
    jobs:
      - build
      - happo:
          requires:
            - build
