version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

commands:
  build_html:
    description: 'Build HTML'
    steps:
      - run: make install
      - run: make build
  run_happo:
    description: 'Run Happo'
    steps:
      - run: find /tmp/html
      - run:
          command: python3 -m http.server 10042
          background: true
          working_directory: /tmp/html
      - run: sleep 10 && make diff

jobs:
  build:
    description: 'Build'
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - checkout
      - build_html
      - persist_to_workspace:
          root: /tmp/html
          paths: '*'
  happo:
    docker:
      - image: 'cimg/node:lts-browsers'
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/html
      - browser-tools/install-browser-tools
      - run_happo

workflows:
  version: 2
  tests:
    jobs:
      - build
      - happo:
          requires:
            - build
